---
# Basic configuration for Packit
# See documentation: https://packit.dev/docs/configuration/

specfile_path: fedora/python-configshell-fb.spec

# Configure files to sync between upstream and downstream
synced_files:
  - .packit.yaml
  - fedora/python-configshell-fb.spec

upstream_package_name: configshell-fb
# In Fedora, Python packages are prefixed with 'python-'
downstream_package_name: python-configshell-fb

# Use Python's build system to create the source archive
actions:
  create-archive:
    - python -m build --sdist
    - bash -c "ls -1t ./dist/*.tar.gz | head -n 1"

jobs:
  # Test PRs in COPR
  - job: copr_build
    trigger: pull_request
    targets:
      - fedora-all
      - epel-9

  # Run tests
  - job: tests
    trigger: pull_request
    targets:
      - fedora-all
      - epel-9

  # Sync with Fedora when a new release is created
  - job: propose_downstream
    trigger: release
    dist_git_branches:
      - fedora-all
      - epel-9
